use crate::gcloud::executor::{GcloudError, GcloudRunner};
use std::path::{Path, PathBuf};

pub struct SshConfigResult {
    pub ssh_host: String,
    pub config_path: String,
}

const GCE_SECTION_START: &str = "# Google Compute Engine Section";
const GCE_SECTION_END: &str = "# End of Google Compute Engine Section";

const GCE_SECTION_HEADER: &str = "#
# The following has been auto-generated by \"gcloud compute config-ssh\"
# to make accessing your Google Compute Engine virtual machines easier.
#
# To remove this blob, run:
#
#   gcloud compute config-ssh --remove
#
# You can also manually remove this blob by deleting everything from
# here until the comment that contains the string \"End of Google Compute
# Engine Section\".
#
# You should not hand-edit this section, unless you are deleting it.
#
";

/// Configure SSH for a GCE instance.
///
/// CLI mode: delegates to `gcloud compute config-ssh` (handles all instances, key rotation, etc.)
/// API mode: writes the SSH host block natively inside the standard gcloud section —
///           no gcloud binary required, and gcloud won't create duplicates if run afterward.
pub async fn configure_ssh(
    runner: &dyn GcloudRunner,
    instance_name: &str,
    zone: &str,
    project: &str,
    external_ip: Option<String>,
) -> Result<SshConfigResult, GcloudError> {
    let ssh_host = format!("{instance_name}.{zone}.{project}");

    if runner.is_cli() {
        runner
            .run(&["compute", "config-ssh", "--project", project, "--quiet"])
            .await?;

        let config_path = ssh_config_path();
        return Ok(SshConfigResult {
            ssh_host,
            config_path: config_path.to_string_lossy().into(),
        });
    }

    // API mode: write the host block natively using the external IP from describe
    let ip = external_ip.ok_or_else(|| GcloudError {
        message: "No external IP available for SSH config (instance may not have a public IP)"
            .into(),
        command: "configure_ssh".into(),
        exit_code: -1,
    })?;

    let key_path = ensure_ssh_key().map_err(|e| GcloudError {
        message: format!("SSH key setup failed: {e}"),
        command: "configure_ssh".into(),
        exit_code: -1,
    })?;

    let config_path = ssh_config_path();
    write_ssh_config(&config_path, &ssh_host, &ip, &key_path).map_err(|e| GcloudError {
        message: format!("Failed to write SSH config: {e}"),
        command: "configure_ssh".into(),
        exit_code: -1,
    })?;

    Ok(SshConfigResult {
        ssh_host,
        config_path: config_path.to_string_lossy().into(),
    })
}

fn ssh_config_path() -> PathBuf {
    dirs::home_dir()
        .map(|h| h.join(".ssh").join("config"))
        .unwrap_or_else(|| PathBuf::from("~/.ssh/config"))
}

/// Write (or replace) a host entry inside the Google Compute Engine section of `~/.ssh/config`.
/// All content outside the GCE section is preserved byte-for-byte.
/// If no GCE section exists, one is created using gcloud's exact format.
pub fn write_ssh_config(
    config_path: &Path,
    ssh_host: &str,
    external_ip: &str,
    key_path: &Path,
) -> Result<(), String> {
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create .ssh directory: {e}"))?;
    }

    let existing = if config_path.exists() {
        std::fs::read_to_string(config_path)
            .map_err(|e| format!("Failed to read SSH config: {e}"))?
    } else {
        String::new()
    };

    let new_entry = build_host_entry(ssh_host, external_ip, key_path);

    let new_content = if let Some((before, body, after)) =
        split_around_gce_section(&existing)
    {
        // Section exists — update or insert the host entry inside it, leave everything else intact
        let updated_body = upsert_host_in_section(body, ssh_host, &new_entry);
        format!("{before}{GCE_SECTION_START}\n{updated_body}{GCE_SECTION_END}\n{after}")
    } else {
        // No section yet — append one using gcloud's standard format
        format!(
            "{existing}\n{GCE_SECTION_START}\n{GCE_SECTION_HEADER}{new_entry}\n{GCE_SECTION_END}\n"
        )
    };

    // Atomic write: temp file → rename
    let dir = config_path.parent().unwrap_or(Path::new("."));
    let tmp_path = dir.join(".ssh_config_tmp");
    std::fs::write(&tmp_path, &new_content)
        .map_err(|e| format!("Failed to write SSH config temp file: {e}"))?;
    std::fs::rename(&tmp_path, config_path)
        .map_err(|e| format!("Failed to rename SSH config: {e}"))?;

    Ok(())
}

/// Build a single host entry in gcloud's exact format (4-space indent, `=` for options).
fn build_host_entry(ssh_host: &str, external_ip: &str, key_path: &Path) -> String {
    let key_display = key_path.to_string_lossy();
    let known_hosts = dirs::home_dir()
        .map(|h| h.join(".ssh").join("google_compute_known_hosts"))
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|| "~/.ssh/google_compute_known_hosts".into());
    format!(
        "Host {ssh_host}\n    HostName {external_ip}\n    IdentityFile {key_display}\n    UserKnownHostsFile={known_hosts}\n    StrictHostKeyChecking=no\n    IdentitiesOnly=yes\n    CheckHostIP=no\n"
    )
}

/// Split `content` around the GCE section, returning `(before, body, after)` where:
/// - `before` is everything up to and including the newline before the start sentinel
/// - `body` is the text between the sentinels (exclusive of sentinel lines themselves)
/// - `after` is everything after the end sentinel line (including its trailing newline)
///
/// All three are byte-exact substrings so reassembly is lossless.
/// Returns `None` if no GCE section is found.
fn split_around_gce_section(content: &str) -> Option<(&str, &str, &str)> {
    // Find start sentinel line
    let start_pos = content.find(GCE_SECTION_START)?;
    // before = everything up to (not including) the start sentinel line
    let before = &content[..start_pos];
    // skip past the start sentinel line (including its newline)
    let after_start = &content[start_pos + GCE_SECTION_START.len()..];
    let after_start = after_start.strip_prefix("\r\n").or_else(|| after_start.strip_prefix('\n')).unwrap_or(after_start);

    // Find end sentinel line within what follows
    let end_pos = after_start.find(GCE_SECTION_END)?;
    let body = &after_start[..end_pos];
    // skip past the end sentinel line (including its newline)
    let remainder = &after_start[end_pos + GCE_SECTION_END.len()..];
    let after = remainder.strip_prefix("\r\n").or_else(|| remainder.strip_prefix('\n')).unwrap_or(remainder);

    Some((before, body, after))
}

/// Within a GCE section body, replace the existing `Host {ssh_host}` block if present,
/// otherwise append the new entry. All other host entries are preserved byte-for-byte.
fn upsert_host_in_section(body: &str, ssh_host: &str, new_entry: &str) -> String {
    let target_header = format!("Host {ssh_host}");
    let mut result = String::with_capacity(body.len() + new_entry.len());
    let mut remaining = body;
    let mut found = false;

    while !remaining.is_empty() {
        let (line_with_ending, rest) = split_first_line(remaining);
        let line = trim_line_ending(line_with_ending);

        if line == target_header {
            // Skip this host block (up to but not including the next Host line or end of body)
            found = true;
            remaining = rest;
            while !remaining.is_empty() {
                let (next_line_with_ending, next_rest) = split_first_line(remaining);
                let next_line = trim_line_ending(next_line_with_ending);
                if next_line.starts_with("Host ") {
                    break; // next host block — stop consuming
                }
                remaining = next_rest;
            }
        } else {
            result.push_str(line_with_ending);
            remaining = rest;
        }
    }

    // Append the new entry (whether replacing or adding)
    let _ = found; // consumed either way
    result.push_str(new_entry);
    result
}

fn split_first_line(s: &str) -> (&str, &str) {
    if let Some(pos) = s.find('\n') {
        (&s[..pos + 1], &s[pos + 1..])
    } else {
        (s, "")
    }
}

fn trim_line_ending(s: &str) -> &str {
    s.trim_end_matches('\n').trim_end_matches('\r')
}

/// Return the path to an SSH private key, generating one at `~/.ssh/google_compute_engine` if needed.
pub fn ensure_ssh_key() -> Result<PathBuf, String> {
    let key_path = dirs::home_dir()
        .map(|h| h.join(".ssh").join("google_compute_engine"))
        .ok_or("Cannot determine home directory")?;

    if key_path.exists() {
        return Ok(key_path);
    }

    let ssh_dir = key_path.parent().unwrap();
    std::fs::create_dir_all(ssh_dir)
        .map_err(|e| format!("Failed to create .ssh directory: {e}"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(ssh_dir, std::fs::Permissions::from_mode(0o700))
            .map_err(|e| format!("Failed to set .ssh permissions: {e}"))?;
    }

    let comment = format!(
        "{}@gce-launcher",
        std::env::var("USER")
            .or_else(|_| std::env::var("USERNAME"))
            .unwrap_or_else(|_| "user".into())
    );

    let status = std::process::Command::new("ssh-keygen")
        .args([
            "-t", "rsa",
            "-b", "3072",
            "-C", &comment,
            "-N", "",
            "-f", &key_path.to_string_lossy(),
        ])
        .status()
        .map_err(|e| format!("Failed to run ssh-keygen: {e}"))?;

    if !status.success() {
        let fallback = dirs::home_dir()
            .map(|h| h.join(".ssh").join("id_rsa"))
            .filter(|p| p.exists());
        if let Some(fb) = fallback {
            return Ok(fb);
        }
        return Err(format!("ssh-keygen exited with status: {status}"));
    }

    Ok(key_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gcloud::executor::{FakeRunner, GcloudError};
    use async_trait::async_trait;
    use tempfile::TempDir;

    /// A FakeRunner that reports itself as CLI mode.
    struct FakeCliRunner(FakeRunner);

    #[async_trait]
    impl GcloudRunner for FakeCliRunner {
        async fn run(&self, args: &[&str]) -> Result<String, GcloudError> {
            self.0.run(args).await
        }
        fn is_cli(&self) -> bool {
            true
        }
    }

    #[tokio::test]
    async fn produces_correct_ssh_host_gcloud_path() {
        let mut inner = FakeRunner::new();
        inner.on_success("compute config-ssh", "");
        let runner = FakeCliRunner(inner);

        let result = configure_ssh(&runner, "my-vm", "us-central1-a", "my-project", None)
            .await
            .unwrap();
        assert_eq!(result.ssh_host, "my-vm.us-central1-a.my-project");
        assert!(result.config_path.contains(".ssh"));
    }

    #[tokio::test]
    async fn propagates_error_on_gcloud_path() {
        let mut inner = FakeRunner::new();
        inner.on_error("compute config-ssh", "ssh error", 1);
        let runner = FakeCliRunner(inner);

        let result = configure_ssh(&runner, "my-vm", "us-central1-a", "my-project", None).await;
        assert!(result.is_err());
    }

    fn key() -> PathBuf {
        PathBuf::from("/home/user/.ssh/google_compute_engine")
    }

    // --- upsert_host_in_section ---

    #[test]
    fn upsert_host_adds_to_empty_section() {
        let entry = build_host_entry("vm.z.p", "1.2.3.4", &key());
        let result = upsert_host_in_section("", "vm.z.p", &entry);
        assert!(result.contains("Host vm.z.p"));
        assert!(result.contains("HostName 1.2.3.4"));
    }

    #[test]
    fn upsert_host_replaces_existing_entry() {
        let old = "Host vm.z.p\n    HostName 1.1.1.1\n    IdentitiesOnly=yes\n\n";
        let new_entry = build_host_entry("vm.z.p", "2.2.2.2", &key());
        let result = upsert_host_in_section(old, "vm.z.p", &new_entry);
        assert_eq!(result.matches("Host vm.z.p").count(), 1);
        assert!(result.contains("HostName 2.2.2.2"));
        assert!(!result.contains("HostName 1.1.1.1"));
    }

    #[test]
    fn upsert_host_preserves_other_hosts() {
        let body = "Host other.z.p\n    HostName 9.9.9.9\n    IdentitiesOnly=yes\n\nHost vm.z.p\n    HostName 1.1.1.1\n    IdentitiesOnly=yes\n\n";
        let new_entry = build_host_entry("vm.z.p", "2.2.2.2", &key());
        let result = upsert_host_in_section(body, "vm.z.p", &new_entry);
        assert!(result.contains("Host other.z.p"));
        assert!(result.contains("HostName 9.9.9.9"));
        assert_eq!(result.matches("Host vm.z.p").count(), 1);
        assert!(result.contains("HostName 2.2.2.2"));
    }

    // --- write_ssh_config ---

    #[test]
    fn write_ssh_config_creates_section_when_missing() {
        let dir = TempDir::new().unwrap();
        let config_path = dir.path().join("config");

        write_ssh_config(&config_path, "vm.z.p", "1.2.3.4", &key()).unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(content.contains(GCE_SECTION_START));
        assert!(content.contains(GCE_SECTION_END));
        assert!(content.contains("Host vm.z.p"));
        assert!(content.contains("HostName 1.2.3.4"));
        assert!(content.contains("IdentitiesOnly=yes"));
    }

    #[test]
    fn write_ssh_config_adds_to_existing_section() {
        let dir = TempDir::new().unwrap();
        let config_path = dir.path().join("config");

        // Pre-populate with a gcloud section containing a different host
        let initial = format!(
            "{GCE_SECTION_START}\n{GCE_SECTION_HEADER}Host other.z.p\n    HostName 9.9.9.9\n    IdentitiesOnly=yes\n\n{GCE_SECTION_END}\n"
        );
        std::fs::write(&config_path, &initial).unwrap();

        write_ssh_config(&config_path, "vm.z.p", "1.2.3.4", &key()).unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        // Only one GCE section
        assert_eq!(content.matches(GCE_SECTION_START).count(), 1);
        assert_eq!(content.matches(GCE_SECTION_END).count(), 1);
        // Both hosts present
        assert!(content.contains("Host other.z.p"));
        assert!(content.contains("Host vm.z.p"));
        assert!(content.contains("HostName 1.2.3.4"));
    }

    #[test]
    fn write_ssh_config_replaces_existing_entry_in_section() {
        let dir = TempDir::new().unwrap();
        let config_path = dir.path().join("config");

        let initial = format!(
            "{GCE_SECTION_START}\n{GCE_SECTION_HEADER}Host vm.z.p\n    HostName 1.1.1.1\n    IdentitiesOnly=yes\n\n{GCE_SECTION_END}\n"
        );
        std::fs::write(&config_path, &initial).unwrap();

        write_ssh_config(&config_path, "vm.z.p", "2.2.2.2", &key()).unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        assert_eq!(content.matches("Host vm.z.p").count(), 1);
        assert!(content.contains("HostName 2.2.2.2"));
        assert!(!content.contains("HostName 1.1.1.1"));
    }

    #[test]
    fn write_ssh_config_preserves_content_outside_section_byte_for_byte() {
        let dir = TempDir::new().unwrap();
        let config_path = dir.path().join("config");

        // Original content with CRLF line endings and irregular whitespace before the GCE section
        let original_prefix = "Host github.com\r\n  User git\r\n\nHost bitbucket.org\n  User hg\n\n";
        let initial = format!(
            "{original_prefix}{GCE_SECTION_START}\n{GCE_SECTION_HEADER}Host old.z.p\n    HostName 9.9.9.9\n    IdentitiesOnly=yes\n\n{GCE_SECTION_END}\n"
        );
        std::fs::write(&config_path, &initial).unwrap();

        write_ssh_config(&config_path, "vm.z.p", "1.2.3.4", &key()).unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        // Everything before the GCE section is byte-for-byte identical
        assert!(
            content.starts_with(original_prefix),
            "content before GCE section was modified"
        );
    }
}
